#import "./fragments.gql"

# Get an order
query orderByReferenceId($id: ID!, $shopId: ID!, $token: String) {
  order: orderByReferenceId(id: $id, shopId: $shopId, token: $token) {
    ...OrderQueryFragment
  }
}

# Get orders by accountId
query ordersByAccountId($accountId: ID!, $shopIds: [ID]) {
  orders: ordersByAccountId(accountId: $accountId, shopIds: $shopIds) {
    ...OrderQueryFragment
  }
}
