#import "./fragments.gql"

# Get an order
query orderByReferenceId($id: ID!, $language: String!, $shopId: ID!, $token: String) {
  order: orderByReferenceId(id: $id, shopId: $shopId, token: $token) {
    ...OrderQueryFragment
  }
}

# Get orders by accountId
query ordersByAccountId($accountId: ID!, $language: String!, $orderStatus: String! = "all", $shopIds: [ID]) {
  orders: ordersByAccountId(accountId: $accountId, orderStatus: $orderStatus, shopIds: $shopIds) {
    totalCount
    pageInfo {
      endCursor
      startCursor
      hasNextPage
      hasPreviousPage
    }
    edges {
      node {
        ...OrderQueryFragment
      }
    }
  }
}
