#import "./fragments.gql"

# Get an order
query orderByReferenceId($id: ID!, $shopId: ID!, $token: String) {
  order: orderByReferenceId(id: $id, shopId: $shopId, token: $token) {
    ...OrderQueryFragment
  }
}
