version: '3.4'

networks:
  api:
    external:
      name: api.reaction.localhost
  auth.reaction.localhost:
    external:
      name: auth.reaction.localhost

services:
  web:
    user: root
    build:
      context: .
      args:
        BUILD_ENV: "development"
    command: "/usr/local/src/reaction-app/bin/start"
    env_file:
      - ./.env
    environment:
      REACTION_APP_NAME: "storefront.web"
    networks:
      api:
        aliases:
          - storefront
      auth.reaction.localhost:
    ports:
      - 4000:4000
    volumes:
      - $HOME/.cache/yarn-offline-mirror:/home/node/.cache/yarn-offline-mirror
      - web-yarn:/home/node/.cache/yarn
      - .:/usr/local/src/reaction-app
      - empty_node_modules:/usr/local/src/reaction-app/node_modules # do not link node_modules in, and persist it between dc up runs
      - node_modules:/usr/local/src/node_modules

volumes:
  web-yarn:
  empty_node_modules:
  node_modules:
