# This docker-compose file is used to run the Example Storefront in Docker for development.
# The local files are mounted into the created container.
# Usage: docker-compose up [-d]

version: '3.4'

networks:
  api:
    external:
      name: api.reaction.localhost
  auth.reaction.localhost:
    external:
      name: auth.reaction.localhost

services:
  web:
    image: reactioncommerce/node-dev:10.16.3-v2
    env_file:
      - ./.env
    networks:
      api:
        aliases:
          - storefront
      auth.reaction.localhost:
    ports:
      - 4000:4000
    volumes:
      - web-yarn:/home/node/.cache/yarn
      - .:/usr/local/src/app
      # Do not link in node_modules from the host
      # This allows IDEs to run lint etc with native add-ons for host OS
      # Without interfering with native add-ons in container
      - empty_node_modules:/usr/local/src/app/node_modules

volumes:
  web-yarn:
  empty_node_modules:
