#import "./navigationFragment.gql"

query navigationQuery($id: ID!, $language: String!) {
  navigationTreeById(id: $id, language: $language) {
    _id
    shopId
    name
    items {
      navigationItem {
        data {
          ...NavigationItemFields
        }
      }
      items {
        navigationItem {
          data {
            ...NavigationItemFields
          }
        }
        items {
          navigationItem {
            data {
              ...NavigationItemFields
            }
          }
        }
      }
    }
  }
}
