#import "../navigation/navigationTreeFragment.gql"

query primaryShop($language: String! = "en") {
  primaryShop {
    _id
    currency {
      code
    }
    defaultNavigationTree(language: $language) {
      ...NavigationTreeFragment
    }
    description
    name
  }
}
