query catalogItemProductQuery($slugOrId: String!) {
  catalogItemProduct(slugOrId: $slugOrId) {
    product {
      _id
      title
      slug
      description
      vendor
      isLowQuantity
      isSoldOut
      isBackorder
      pricing {
        currency {
          code
        }
        displayPrice
      }
      media {
        toGrid
        priority
        productId
        variantId
        URLs {
          thumbnail
          small
          medium
          large
          original
        }
      }
      tags {
        nodes {
          name
          slug
          position
        }
      }
      variants {
        _id
        variantId
        title
        optionTitle
        pricing {
          currency {
            code
          }
          displayPrice
        }
        options {
          _id
          variantId
          title
          pricing {
            currency {
              code
            }
            displayPrice
          }
          optionTitle
          isSoldOut
          isLowQuantity
        }
      }
    }
  }
}
