export const tempProducts = [
  {
    _id: "h2v7MYCXBtjMm7Piv",
    type: "simple",
    ancestors: [],
    shopId: "J8Bhq3uTtdgwZx3rz",
    title: "Reaction Bag of Beans",
    originCountry: "US",
    requiresShipping: true,
    handle: "reaction-bag-of-beans",
    isDeleted: false,
    isVisible: true,
    template: "productDetailSimple",
    price: {
      range: "12 - 24",
      min: 12,
      max: 24
    },
    workflow: {
      status: "new"
    },
    isLowQuantity: false,
    isSoldOut: true,
    vendor: "Bluestone Coffee",
    description:
      "A bag of rich Arabica coffee. Great for a fueling up for a night out or for settling in for a night of coding at home",
    isBackorder: true,
    positions: {
      "reaction swag shop": {
        weight: 1
      }
    },
    hashtags: ["hZdSevCBP8dDc66Ba"]
  },
  {
    _id: "PH8xNGE8pRHdPo8Qc",
    ancestors: ["h2v7MYCXBtjMm7Piv"],
    price: 0,
    type: "variant",
    isVisible: true,
    isDeleted: false,
    compareAtPrice: 0,
    weight: 0,
    length: 0,
    width: 0,
    height: 0,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    inventoryQuantity: 0,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    title: "Bag",
    optionTitle: "Untitled Option",
    originCountry: "US",
    workflow: {
      status: "new"
    }
  },
  {
    _id: "sxW4riWptXTyXN6W7",
    ancestors: ["h2v7MYCXBtjMm7Piv", "PH8xNGE8pRHdPo8Qc"],
    type: "variant",
    title: "One pound bag",
    price: 12,
    isVisible: true,
    isDeleted: false,
    compareAtPrice: 15,
    weight: 2,
    length: 2,
    width: 2,
    height: 2,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    inventoryQuantity: 1000,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "One pound bag",
    originCountry: "US",
    workflow: {
      status: "new"
    }
  },
  {
    _id: "Nsm4GmyerWC7wnwML",
    ancestors: ["h2v7MYCXBtjMm7Piv", "PH8xNGE8pRHdPo8Qc"],
    type: "variant",
    title: "Two pound bag",
    price: 24,
    isVisible: true,
    isDeleted: false,
    compareAtPrice: 28,
    weight: 4,
    length: 4,
    width: 4,
    height: 4,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    inventoryQuantity: 1000,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "Two pound bag",
    originCountry: "US",
    workflow: {
      status: "new"
    }
  },
  {
    _id: "z6paQqnrGnWBvepyB",
    type: "simple",
    ancestors: [],
    shopId: "J8Bhq3uTtdgwZx3rz",
    title: "Reaction Mug",
    originCountry: "US",
    requiresShipping: true,
    handle: "reaction-mug",
    isDeleted: false,
    isVisible: true,
    template: "productDetailSimple",
    price: {
      range: "15",
      min: 15,
      max: 15
    },
    workflow: {
      status: "new"
    },
    isLowQuantity: false,
    isSoldOut: true,
    vendor: "Mugworks",
    description: "A sturdy mug to keep your hot drinks hot and your cold drinks cold",
    isBackorder: true,
    positions: {
      "reaction swag shop": {
        weight: 1
      }
    },
    hashtags: ["hZdSevCBP8dDc66Ba"]
  },
  {
    _id: "oWNyqhaeyw9eKdZKv",
    ancestors: ["z6paQqnrGnWBvepyB"],
    price: 15,
    type: "variant",
    isVisible: true,
    isDeleted: false,
    compareAtPrice: 22,
    weight: 1,
    length: 1,
    width: 1,
    height: 1,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    inventoryQuantity: 1999,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    title: "One Size",
    optionTitle: "Untitled Option",
    originCountry: "US",
    workflow: {
      status: "new"
    }
  },
  {
    _id: "gygxrADdPPWoCCmS7",
    type: "simple",
    ancestors: [],
    shopId: "J8Bhq3uTtdgwZx3rz",
    title: "Reaction Commerce Pouch",
    originCountry: "US",
    requiresShipping: true,
    handle: "reaction-commerce-pouch",
    isDeleted: false,
    isVisible: true,
    template: "productDetailSimple",
    price: {
      range: "8",
      min: 8,
      max: 8
    },
    workflow: {
      status: "new"
    },
    vendor: "Pouchworks",
    description: "Need a small pouch to keep things in? This is your ticket",
    isLowQuantity: false,
    isSoldOut: false,
    isBackorder: false,
    hashtags: ["hZdSevCBP8dDc66Ba"]
  },
  {
    _id: "zhXWhcsisSexE9bg8",
    ancestors: ["gygxrADdPPWoCCmS7"],
    price: 8,
    type: "variant",
    isVisible: true,
    isDeleted: false,
    compareAtPrice: 10,
    weight: 1,
    length: 1,
    width: 1,
    height: 1,
    inventoryManagement: true,
    inventoryPolicy: true,
    lowInventoryWarningThreshold: 0,
    inventoryQuantity: 1000,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    title: "One Size",
    optionTitle: "Untitled Option",
    originCountry: "US",
    workflow: {
      status: "new"
    }
  },
  {
    _id: "ioKwBYk6Nom9K92cv",
    type: "simple",
    ancestors: [],
    shopId: "J8Bhq3uTtdgwZx3rz",
    title: "Reaction Scout Book",
    originCountry: "US",
    requiresShipping: true,
    handle: "reaction-scout-book",
    isDeleted: false,
    isVisible: true,
    template: "productDetailSimple",
    price: {
      range: "6",
      min: 6,
      max: 6
    },
    workflow: {
      status: "new"
    },
    isLowQuantity: false,
    isSoldOut: true,
    vendor: "Bookworks",
    description:
      "Need to make a quick note? Got a once-in-a-lifetime idea? Write it down in one of these great little notebooks",
    isBackorder: true,
    hashtags: ["hZdSevCBP8dDc66Ba"]
  },
  {
    _id: "ddzkNjFJ3MjfkzvMg",
    ancestors: ["ioKwBYk6Nom9K92cv"],
    price: 6,
    type: "variant",
    isVisible: true,
    isDeleted: false,
    compareAtPrice: 8,
    weight: 1,
    length: 1,
    width: 1,
    height: 1,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    inventoryQuantity: 1000,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    title: "One Size",
    optionTitle: "Untitled Option",
    originCountry: "US",
    workflow: {
      status: "new"
    }
  },
  {
    _id: "xsudQc3K2EbqCeFBm",
    type: "simple",
    ancestors: [],
    shopId: "J8Bhq3uTtdgwZx3rz",
    title: "Reaction Ladies Shirt",
    originCountry: "US",
    requiresShipping: true,
    handle: "reaction-ladies-shirt",
    isDeleted: false,
    isVisible: true,
    template: "productDetailSimple",
    price: {
      range: "18 - 20",
      min: 18,
      max: 20
    },
    workflow: {
      status: "new"
    },
    isLowQuantity: false,
    isSoldOut: true,
    vendor: "Shirtworks",
    description:
      "The same hip Reaction logo in a cut more suitable for the ladies. 100% cotton fabric and double-stitching make this a shirt that will last for years to come",
    isBackorder: true,
    hashtags: ["dhqmJjXWotCNkTzxg"]
  },
  {
    _id: "78zu2u3in4rNrWtKt",
    ancestors: ["xsudQc3K2EbqCeFBm"],
    price: 18,
    type: "variant",
    isVisible: true,
    isDeleted: false,
    compareAtPrice: 24,
    weight: 0,
    length: 2,
    width: 2,
    height: 2,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    inventoryQuantity: 0,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    title: "Blue",
    optionTitle: "Untitled Option",
    originCountry: "US",
    workflow: {
      status: "new"
    }
  },
  {
    _id: "sznWKKjZKirqmots9",
    ancestors: ["xsudQc3K2EbqCeFBm", "78zu2u3in4rNrWtKt"],
    type: "variant",
    title: "SM",
    price: 18,
    isVisible: true,
    isDeleted: false,
    compareAtPrice: 24,
    weight: 1,
    length: 1,
    width: 1,
    height: 1,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    inventoryQuantity: 200,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "Small",
    originCountry: "US",
    workflow: {
      status: "new"
    }
  },
  {
    _id: "L4TCjAdBwxPERZq4x",
    ancestors: ["xsudQc3K2EbqCeFBm", "78zu2u3in4rNrWtKt"],
    type: "variant",
    title: "M",
    price: 18,
    isVisible: true,
    isDeleted: false,
    compareAtPrice: 24,
    weight: 2,
    length: 2,
    width: 2,
    height: 2,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    inventoryQuantity: 1000,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "Medium",
    originCountry: "US",
    workflow: {
      status: "new"
    }
  },
  {
    _id: "m2xTjjeCzLpb7J2vc",
    ancestors: ["xsudQc3K2EbqCeFBm", "78zu2u3in4rNrWtKt"],
    type: "variant",
    title: "L",
    price: 18,
    isVisible: true,
    isDeleted: false,
    compareAtPrice: 24,
    weight: 1,
    length: 1,
    width: 1,
    height: 1,
    inventoryManagement: true,
    inventoryPolicy: true,
    lowInventoryWarningThreshold: 0,
    inventoryQuantity: 1000,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "Large",
    originCountry: "US",
    workflow: {
      status: "new"
    }
  },
  {
    _id: "NvjcjqppXzeX9nuNQ",
    ancestors: ["xsudQc3K2EbqCeFBm", "78zu2u3in4rNrWtKt"],
    type: "variant",
    title: "XL",
    price: 20,
    isVisible: true,
    isDeleted: false,
    compareAtPrice: 26,
    weight: 1,
    length: 1,
    width: 1,
    height: 1,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    inventoryQuantity: 1000,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "Extra-Large",
    originCountry: "US",
    workflow: {
      status: "new"
    }
  },
  {
    _id: "GpZM5v5qQBCdXsoqW",
    type: "simple",
    ancestors: [],
    shopId: "J8Bhq3uTtdgwZx3rz",
    title: "Reaction Mens Shirt",
    originCountry: "US",
    requiresShipping: true,
    isDeleted: false,
    isVisible: true,
    template: "productDetailSimple",
    price: {
      range: "18 - 20",
      min: 18,
      max: 20
    },
    workflow: {
      status: "new"
    },
    isLowQuantity: false,
    isSoldOut: true,
    vendor: "Shirtworks",
    description:
      "Get your Reaction together and show it to the world. 100% cotton fabric and double-stitching make this a shirt that will last for years to come",
    isBackorder: true,
    handle: "reaction-mens-shirt",
    hashtags: ["dhqmJjXWotCNkTzxg"]
  },
  {
    _id: "cxYA8s8qdi8qnYSNw",
    ancestors: ["GpZM5v5qQBCdXsoqW"],
    price: 18,
    type: "variant",
    isVisible: true,
    isDeleted: false,
    compareAtPrice: 24,
    weight: 0,
    length: 2,
    width: 2,
    height: 2,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    inventoryQuantity: 0,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    title: "Blue",
    optionTitle: "Untitled Option",
    originCountry: "US",
    workflow: {
      status: "new"
    }
  },
  {
    _id: "TC9i4PfCEGLGgjxMa",
    shopId: "J8Bhq3uTtdgwZx3rz",
    ancestors: ["GpZM5v5qQBCdXsoqW", "cxYA8s8qdi8qnYSNw"],
    lowInventoryWarningThreshold: 0,
    price: 18,
    height: 1,
    compareAtPrice: 24,
    originCountry: "US",
    weight: 1,
    workflow: {
      status: "new"
    },
    inventoryPolicy: false,
    length: 1,
    type: "variant",
    taxable: true,
    inventoryManagement: true,
    taxCode: "0000",
    isDeleted: false,
    inventoryQuantity: 200,
    isVisible: true,
    optionTitle: "Small",
    width: 1,
    title: "SM"
  },
  {
    _id: "u7BcWyqS9WHc4zDfJ",
    shopId: "J8Bhq3uTtdgwZx3rz",
    ancestors: ["GpZM5v5qQBCdXsoqW", "cxYA8s8qdi8qnYSNw"],
    lowInventoryWarningThreshold: 0,
    price: 18,
    height: 2,
    compareAtPrice: 24,
    originCountry: "US",
    weight: 2,
    workflow: {
      status: "new"
    },
    inventoryPolicy: false,
    length: 2,
    type: "variant",
    taxable: true,
    inventoryManagement: true,
    taxCode: "0000",
    isDeleted: false,
    inventoryQuantity: 1000,
    isVisible: true,
    optionTitle: "Medium",
    width: 2,
    title: "M"
  },
  {
    _id: "eJQdg8nQ3g7LJJXWJ",
    shopId: "J8Bhq3uTtdgwZx3rz",
    ancestors: ["GpZM5v5qQBCdXsoqW", "cxYA8s8qdi8qnYSNw"],
    lowInventoryWarningThreshold: 0,
    price: 18,
    height: 1,
    compareAtPrice: 24,
    originCountry: "US",
    weight: 1,
    workflow: {
      status: "new"
    },
    inventoryPolicy: true,
    length: 1,
    type: "variant",
    taxable: true,
    inventoryManagement: true,
    taxCode: "0000",
    isDeleted: false,
    inventoryQuantity: 1000,
    isVisible: true,
    optionTitle: "Large",
    width: 1,
    title: "L"
  },
  {
    _id: "RYqHfoqpQBWc53Apo",
    shopId: "J8Bhq3uTtdgwZx3rz",
    ancestors: ["GpZM5v5qQBCdXsoqW", "cxYA8s8qdi8qnYSNw"],
    lowInventoryWarningThreshold: 0,
    price: 20,
    height: 1,
    compareAtPrice: 26,
    originCountry: "US",
    weight: 1,
    workflow: {
      status: "new"
    },
    inventoryPolicy: false,
    length: 1,
    type: "variant",
    taxable: true,
    inventoryManagement: true,
    taxCode: "0000",
    isDeleted: false,
    inventoryQuantity: 1000,
    isVisible: true,
    optionTitle: "Extra-Large",
    width: 1,
    title: "XL"
  },
  {
    _id: "9zxhE27pAvx8vbKr5",
    type: "simple",
    ancestors: [],
    shopId: "J8Bhq3uTtdgwZx3rz",
    title: "Reaction Sticker",
    originCountry: "US",
    requiresShipping: true,
    handle: "reaction-sticker",
    isDeleted: false,
    isVisible: true,
    template: "productDetailSimple",
    price: {
      range: "4",
      min: 4,
      max: 4
    },
    workflow: {
      status: "new"
    },
    isLowQuantity: false,
    isSoldOut: true,
    vendor: "Stickerworks",
    description: "Show your pride and affix some Reaction to almost any surface",
    isBackorder: true,
    hashtags: ["hZdSevCBP8dDc66Ba"]
  },
  {
    _id: "aXsSSpddrPcBWppFK",
    ancestors: ["9zxhE27pAvx8vbKr5"],
    price: 4,
    type: "variant",
    isVisible: true,
    isDeleted: false,
    compareAtPrice: 6,
    weight: 1,
    length: 1,
    width: 1,
    height: 1,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    inventoryQuantity: 1000,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    title: "One Size",
    optionTitle: "Untitled Option",
    originCountry: "US",
    workflow: {
      status: "new"
    }
  },
  {
    _id: "5pe6Y2sxKy5eppGMF",
    type: "simple",
    isVisible: true,
    ancestors: [],
    title: "Reaction Hoodie",
    originCountry: "US",
    requiresShipping: true,
    handle: "reaction-hoodie",
    isDeleted: false,
    shopId: "J8Bhq3uTtdgwZx3rz",
    template: "productDetailSimple",
    workflow: {
      status: "new"
    },
    price: {
      range: "35",
      min: 35,
      max: 35
    },
    vendor: "Hanes",
    description:
      "Whether DJ'ing your EDM set or hacking into the NSA this stylish hoodie will keep your tiny fragile body warm",
    pageTitle: "Keep yourself warm while still representing your favorite open-source ecommerce platform",
    hashtags: ["dhqmJjXWotCNkTzxg"]
  },
  {
    _id: "TsKXj4hugyJxuWQaR",
    type: "variant",
    ancestors: ["5pe6Y2sxKy5eppGMF"],
    price: 0,
    inventoryQuantity: 0,
    isDeleted: false,
    compareAtPrice: 0,
    weight: 0,
    length: 0,
    width: 0,
    height: 0,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    isVisible: true,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    title: "Black",
    optionTitle: "Untitled Option",
    workflow: {
      status: "new"
    },
    originCountry: "US"
  },
  {
    _id: "47SvKpw4Y2u9tQkqg",
    ancestors: ["5pe6Y2sxKy5eppGMF", "TsKXj4hugyJxuWQaR"],
    type: "variant",
    title: "S",
    price: 35,
    inventoryQuantity: 100,
    isDeleted: false,
    compareAtPrice: 55,
    weight: 4,
    length: 23,
    width: 19,
    height: 3,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    isVisible: true,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "Small",
    workflow: {
      status: "new"
    },
    originCountry: "US"
  },
  {
    _id: "RTgxXqqHD69C5sGaZ",
    ancestors: ["5pe6Y2sxKy5eppGMF", "TsKXj4hugyJxuWQaR"],
    type: "variant",
    title: "M",
    price: 35,
    inventoryQuantity: 100,
    isDeleted: false,
    compareAtPrice: 55,
    weight: 4,
    length: 23,
    width: 19,
    height: 3,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    isVisible: true,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "Medium",
    workflow: {
      status: "new"
    },
    originCountry: "US"
  },
  {
    _id: "LZ7mWgohWDxDCxqbg",
    ancestors: ["5pe6Y2sxKy5eppGMF", "TsKXj4hugyJxuWQaR"],
    type: "variant",
    title: "L",
    price: 35,
    inventoryQuantity: 100,
    isDeleted: false,
    compareAtPrice: 55,
    weight: 4,
    length: 23,
    width: 19,
    height: 3,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    isVisible: true,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "Large",
    workflow: {
      status: "new"
    },
    originCountry: "US"
  },
  {
    _id: "fs6MdddZgQLEXFqLR",
    ancestors: ["5pe6Y2sxKy5eppGMF", "TsKXj4hugyJxuWQaR"],
    type: "variant",
    title: "XL",
    price: 35,
    inventoryQuantity: 100,
    isDeleted: false,
    compareAtPrice: 55,
    weight: 4,
    length: 23,
    width: 19,
    height: 3,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    isVisible: true,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "X-Large",
    workflow: {
      status: "new"
    },
    originCountry: "US"
  },
  {
    _id: "Ks3fNppgpv4G8R4gt",
    type: "simple",
    isVisible: true,
    ancestors: [],
    title: "Reaction Camp Shirt",
    originCountry: "US",
    requiresShipping: true,
    isDeleted: false,
    shopId: "J8Bhq3uTtdgwZx3rz",
    template: "productDetailSimple",
    workflow: {
      status: "new"
    },
    price: {
      range: "40 - 45",
      min: 40,
      max: 45
    },
    vendor: "Hanes",
    description:
      "This camp shirt is a classy, clean alternative to T-shirts or Polos. Represent Reaction at camp or on the road",
    pageTitle: "Stylish but casual",
    hashtags: ["dhqmJjXWotCNkTzxg"],
    handle: "reaction-camp-shirt"
  },
  {
    _id: "wxAThpm5Cv5j6ozjY",
    type: "variant",
    ancestors: ["Ks3fNppgpv4G8R4gt"],
    price: 0,
    inventoryQuantity: 0,
    isDeleted: false,
    compareAtPrice: 0,
    weight: 0,
    length: 0,
    width: 0,
    height: 0,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    isVisible: true,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    title: "Black",
    optionTitle: "Untitled Option",
    workflow: {
      status: "new"
    },
    originCountry: "US"
  },
  {
    _id: "b9GkPWqBNkxhArTPJ",
    ancestors: ["Ks3fNppgpv4G8R4gt", "wxAThpm5Cv5j6ozjY"],
    type: "variant",
    title: "S",
    price: 40,
    inventoryQuantity: 100,
    isDeleted: false,
    compareAtPrice: 55,
    weight: 4,
    length: 23,
    width: 19,
    height: 3,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    isVisible: true,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "Small",
    workflow: {
      status: "new"
    },
    originCountry: "US"
  },
  {
    _id: "x8sJGkbYxg2iRYMFM",
    ancestors: ["Ks3fNppgpv4G8R4gt", "wxAThpm5Cv5j6ozjY"],
    type: "variant",
    title: "M",
    price: 40,
    inventoryQuantity: 100,
    isDeleted: false,
    compareAtPrice: 55,
    weight: 4,
    length: 23,
    width: 19,
    height: 3,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    isVisible: true,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "Medium",
    workflow: {
      status: "new"
    },
    originCountry: "US"
  },
  {
    _id: "X6uN3h6ASh37PpF7b",
    ancestors: ["Ks3fNppgpv4G8R4gt", "wxAThpm5Cv5j6ozjY"],
    type: "variant",
    title: "L",
    price: 45,
    inventoryQuantity: 100,
    isDeleted: false,
    compareAtPrice: 55,
    weight: 4,
    length: 23,
    width: 19,
    height: 3,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    isVisible: true,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "Large",
    workflow: {
      status: "new"
    },
    originCountry: "US"
  },
  {
    _id: "ZqEeYurYBa6N9cWpL",
    ancestors: ["Ks3fNppgpv4G8R4gt", "wxAThpm5Cv5j6ozjY"],
    type: "variant",
    title: "XL",
    price: 45,
    inventoryQuantity: 100,
    isDeleted: false,
    compareAtPrice: 55,
    weight: 4,
    length: 23,
    width: 19,
    height: 3,
    inventoryManagement: true,
    inventoryPolicy: false,
    lowInventoryWarningThreshold: 0,
    isVisible: true,
    shopId: "J8Bhq3uTtdgwZx3rz",
    taxable: true,
    taxCode: "0000",
    optionTitle: "X-Large",
    workflow: {
      status: "new"
    },
    originCountry: "US"
  }
];
