#import "./fragments.gql"

# place an order
mutation placeOrder($input: PlaceOrderInput!, $language: String! = "en") {
  placeOrder(input: $input) {
    orders {
      ...OrderQueryFragment
    },
    token
  }
}
